/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidesRouteImport } from './routes/valides'
import { Route as SuperviseursRouteImport } from './routes/superviseurs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CritiquesRouteImport } from './routes/critiques'
import { Route as ChargementRouteImport } from './routes/chargement'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'
import { Route as AppelsIdRouteImport } from './routes/appels.$id'

const ValidesRoute = ValidesRouteImport.update({
  id: '/valides',
  path: '/valides',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperviseursRoute = SuperviseursRouteImport.update({
  id: '/superviseurs',
  path: '/superviseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CritiquesRoute = CritiquesRouteImport.update({
  id: '/critiques',
  path: '/critiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargementRoute = ChargementRouteImport.update({
  id: '/chargement',
  path: '/chargement',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsIdRoute = AppelsIdRouteImport.update({
  id: '/appels/$id',
  path: '/appels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/chargement': typeof ChargementRoute
  '/critiques': typeof CritiquesRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superviseurs': typeof SuperviseursRoute
  '/valides': typeof ValidesRoute
  '/appels/$id': typeof AppelsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/chargement': typeof ChargementRoute
  '/critiques': typeof CritiquesRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superviseurs': typeof SuperviseursRoute
  '/valides': typeof ValidesRoute
  '/appels/$id': typeof AppelsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier': typeof CalendrierRoute
  '/chargement': typeof ChargementRoute
  '/critiques': typeof CritiquesRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superviseurs': typeof SuperviseursRoute
  '/valides': typeof ValidesRoute
  '/appels/$id': typeof AppelsIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier'
    | '/chargement'
    | '/critiques'
    | '/login'
    | '/parametres'
    | '/profil'
    | '/reset-password'
    | '/superviseurs'
    | '/valides'
    | '/appels/$id'
    | '/dossiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier'
    | '/chargement'
    | '/critiques'
    | '/login'
    | '/parametres'
    | '/profil'
    | '/reset-password'
    | '/superviseurs'
    | '/valides'
    | '/appels/$id'
    | '/dossiers/$id'
  id:
    | '__root__'
    | '/'
    | '/calendrier'
    | '/chargement'
    | '/critiques'
    | '/login'
    | '/parametres'
    | '/profil'
    | '/reset-password'
    | '/superviseurs'
    | '/valides'
    | '/appels/$id'
    | '/dossiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierRoute: typeof CalendrierRoute
  ChargementRoute: typeof ChargementRoute
  CritiquesRoute: typeof CritiquesRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperviseursRoute: typeof SuperviseursRoute
  ValidesRoute: typeof ValidesRoute
  AppelsIdRoute: typeof AppelsIdRoute
  DossiersIdRoute: typeof DossiersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valides': {
      id: '/valides'
      path: '/valides'
      fullPath: '/valides'
      preLoaderRoute: typeof ValidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superviseurs': {
      id: '/superviseurs'
      path: '/superviseurs'
      fullPath: '/superviseurs'
      preLoaderRoute: typeof SuperviseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critiques': {
      id: '/critiques'
      path: '/critiques'
      fullPath: '/critiques'
      preLoaderRoute: typeof CritiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chargement': {
      id: '/chargement'
      path: '/chargement'
      fullPath: '/chargement'
      preLoaderRoute: typeof ChargementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels/$id': {
      id: '/appels/$id'
      path: '/appels/$id'
      fullPath: '/appels/$id'
      preLoaderRoute: typeof AppelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierRoute: CalendrierRoute,
  ChargementRoute: ChargementRoute,
  CritiquesRoute: CritiquesRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperviseursRoute: SuperviseursRoute,
  ValidesRoute: ValidesRoute,
  AppelsIdRoute: AppelsIdRoute,
  DossiersIdRoute: DossiersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
